[tool.poetry]
name = "Pokemon-Gen3"
version = "0.0.0a2"
description = ""
authors = ["ijknabla <ijknabla@gmail.com>"]
include = ["**/*.db"]

[tool.poetry.build]
script = "build.py"
generate-setup-file = false

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
mypy = "^0.931"
pytest = "^7.0.1"
pyproject-flake8 = "^0.0.1-alpha.2"
types-setuptools = "^57.4.11"
numpy = "^1.20"
requests = "^2.28.1"
lxml = "^4.9.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79

[tool.flake8]
exclude = '.venv'

[tool.mypy]
exclude = [
    "^build/",
]
