CREATE TABLE nature_names
(
    nature_id INTEGER,
    language_id TEXT CHECK(language_id IN ('en', 'jp')),
    name TEXT UNIQUE NOT NULL,
    PRIMARY KEY(nature_id, language_id)
);

INSERT INTO nature_names
    (nature_id, language_id, name        )
VALUES
    (        0, 'en'       , 'Hardly'    ),
    (        1, 'en'       , 'Lonely'    ),
    (        2, 'en'       , 'Brave'     ),
    (        3, 'en'       , 'Adamant'   ),
    (        4, 'en'       , 'Naughty'   ),
    (        5, 'en'       , 'Bold'      ),
    (        6, 'en'       , 'Docile'    ),
    (        7, 'en'       , 'Relaxed'   ),
    (        8, 'en'       , 'Impish'    ),
    (        9, 'en'       , 'Lax'       ),
    (       10, 'en'       , 'Timid'     ),
    (       11, 'en'       , 'Hasty'     ),
    (       12, 'en'       , 'Serious'   ),
    (       13, 'en'       , 'Jolly'     ),
    (       14, 'en'       , 'Naive'     ),
    (       15, 'en'       , 'Modest'    ),
    (       16, 'en'       , 'Mild'      ),
    (       17, 'en'       , 'Quiet'     ),
    (       18, 'en'       , 'Bashful'   ),
    (       19, 'en'       , 'Rash'      ),
    (       20, 'en'       , 'Calm'      ),
    (       21, 'en'       , 'Gentle'    ),
    (       22, 'en'       , 'Sassy'     ),
    (       23, 'en'       , 'Careful'   ),
    (       24, 'en'       , 'Quirky'    ),
    (        0, 'jp'       , 'がんばりや'),
    (        1, 'jp'       , 'さみしがり'),
    (        2, 'jp'       , 'ゆうかん'  ),
    (        3, 'jp'       , 'いじっぱり'),
    (        4, 'jp'       , 'やんちゃ'  ),
    (        5, 'jp'       , 'ずぶとい'  ),
    (        6, 'jp'       , 'すなお'    ),
    (        7, 'jp'       , 'のんき'    ),
    (        8, 'jp'       , 'わんぱく'  ),
    (        9, 'jp'       , 'のうてんき'),
    (       10, 'jp'       , 'おくびょう'),
    (       11, 'jp'       , 'せっかち'  ),
    (       12, 'jp'       , 'まじめ'    ),
    (       13, 'jp'       , 'ようき'    ),
    (       14, 'jp'       , 'むじゃき'  ),
    (       15, 'jp'       , 'ひかえめ'  ),
    (       16, 'jp'       , 'おっとり'  ),
    (       17, 'jp'       , 'れいせい'  ),
    (       18, 'jp'       , 'てれや'    ),
    (       19, 'jp'       , 'うっかりや'),
    (       20, 'jp'       , 'おだやか'  ),
    (       21, 'jp'       , 'おとなしい'),
    (       22, 'jp'       , 'なまいき'  ),
    (       23, 'jp'       , 'しんちょう'),
    (       24, 'jp'       , 'きまぐれ'  );
